"""add_missing_indexes

Revision ID: e419d25831a7
Revises: 5163cac316ad
Create Date: 2025-12-08 13:24:45.368087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers used by Alembic.
revision = 'e419d25831a7'
down_revision = '5163cac316ad'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_allocation_requests_experiment_name'), 'allocation_requests', ['experiment_name'], unique=False)
    op.create_index(op.f('ix_allocation_requests_requester'), 'allocation_requests', ['requester'], unique=False)
    op.create_index(op.f('ix_allocation_requests_status'), 'allocation_requests', ['status'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_device_allocations_experiment_name'), 'device_allocations', ['experiment_name'], unique=False)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_index(op.f('ix_resource_allocations_experiment_name'), 'resource_allocations', ['experiment_name'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_resource_allocations_experiment_name'), table_name='resource_allocations')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_device_allocations_experiment_name'), table_name='device_allocations')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_allocation_requests_status'), table_name='allocation_requests')
    op.drop_index(op.f('ix_allocation_requests_requester'), table_name='allocation_requests')
    op.drop_index(op.f('ix_allocation_requests_experiment_name'), table_name='allocation_requests')
    # ### end Alembic commands ###
