"""normalize_allocation_request_items

Revision ID: 1a76b054d691
Revises: e419d25831a7
Create Date: 2025-12-08 13:35:49.154600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers used by Alembic.
revision = '1a76b054d691'
down_revision = 'e419d25831a7'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_request_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lab_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['allocation_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alloc_req_devices_request_lab', 'allocation_request_devices', ['request_id', 'lab_name'], unique=False)
    op.create_index(op.f('ix_allocation_request_devices_lab_name'), 'allocation_request_devices', ['lab_name'], unique=False)
    op.create_index(op.f('ix_allocation_request_devices_request_id'), 'allocation_request_devices', ['request_id'], unique=False)
    op.create_table('allocation_request_resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lab_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['allocation_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alloc_req_resources_request_lab', 'allocation_request_resources', ['request_id', 'lab_name'], unique=False)
    op.create_index(op.f('ix_allocation_request_resources_lab_name'), 'allocation_request_resources', ['lab_name'], unique=False)
    op.create_index(op.f('ix_allocation_request_resources_request_id'), 'allocation_request_resources', ['request_id'], unique=False)
    op.drop_column('allocation_requests', 'allocations')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allocation_requests', sa.Column('allocations', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_allocation_request_resources_request_id'), table_name='allocation_request_resources')
    op.drop_index(op.f('ix_allocation_request_resources_lab_name'), table_name='allocation_request_resources')
    op.drop_index('idx_alloc_req_resources_request_lab', table_name='allocation_request_resources')
    op.drop_table('allocation_request_resources')
    op.drop_index(op.f('ix_allocation_request_devices_request_id'), table_name='allocation_request_devices')
    op.drop_index(op.f('ix_allocation_request_devices_lab_name'), table_name='allocation_request_devices')
    op.drop_index('idx_alloc_req_devices_request_lab', table_name='allocation_request_devices')
    op.drop_table('allocation_request_devices')
    # ### end Alembic commands ###
