"""add_specifications

Revision ID: 133397a64a1e
Revises: 043566da38f3
Create Date: 2025-10-24 16:41:55.562935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers used by Alembic.
revision = '133397a64a1e'
down_revision = '043566da38f3'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'specifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('spec_type', sa.String(), nullable=False),
        sa.Column('spec_name', sa.String(), nullable=False),
        sa.Column('spec_data', sa.JSON(), nullable=False),
        sa.Column('is_loaded', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('package_name', sa.String(), nullable=False),
        sa.Column('source_path', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spec_type_name', 'specifications', ['spec_type', 'spec_name'], unique=True)
    op.create_index('idx_spec_type', 'specifications', ['spec_type'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_spec_type', table_name='specifications')
    op.drop_index('idx_spec_type_name', table_name='specifications')
    op.drop_table('specifications')
    # ### end Alembic commands ###
