"""add_resource_lab

Revision ID: cdfd9928697a
Revises: 133397a64a1e
Create Date: 2025-10-24 16:44:20.432249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers used by Alembic.
revision = 'cdfd9928697a'
down_revision = '133397a64a1e'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('lab', sa.String(), nullable=True))
    op.create_index('ix_resources_lab', 'resources', ['lab'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resources_lab', table_name='resources')
    op.drop_column('resources', 'lab')
    # ### end Alembic commands ###
