"""Split allocations into device and resource tables

Revision ID: 5163cac316ad
Revises: 2e41a9d10499
Create Date: 2025-12-08 12:44:20.786901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers used by Alembic.
revision = '5163cac316ad'
down_revision = '2e41a9d10499'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lab_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('experiment_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_name'], ['experiments.name'], ),
    sa.ForeignKeyConstraint(['lab_name', 'name'], ['devices.lab_name', 'devices.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_allocation_lab_name_name', 'device_allocations', ['lab_name', 'name'], unique=True)
    op.create_table('resource_allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('experiment_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_name'], ['experiments.name'], ),
    sa.ForeignKeyConstraint(['name'], ['resources.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_index(op.f('idx_allocation_type_lab_name_name'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_allocation_type'), table_name='allocations')
    op.drop_table('allocations')
    op.execute('DROP TYPE IF EXISTS allocationtype')

def downgrade():
    op.execute("CREATE TYPE allocationtype AS ENUM ('RESOURCE', 'DEVICE')")
    op.create_table('allocations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('allocation_type', postgresql.ENUM('RESOURCE', 'DEVICE', name='allocationtype'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lab_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('item_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('experiment_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_name'], ['experiments.name'], name=op.f('allocations_experiment_name_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('allocations_pkey'))
    )
    op.create_index(op.f('ix_allocations_allocation_type'), 'allocations', ['allocation_type'], unique=False)
    op.create_index(op.f('idx_allocation_type_lab_name_name'), 'allocations', ['allocation_type', 'lab_name', 'name'], unique=True)
    op.drop_table('resource_allocations')
    op.drop_index('idx_device_allocation_lab_name_name', table_name='device_allocations')
    op.drop_table('device_allocations')
    # ### end Alembic commands ###
