"""add user roles

Revision ID: 7f5a39e7cf9f
Revises: d5edd32a9495
Create Date: 2026-06-12 14:06:12.950479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers used by Alembic.
revision = '7f5a39e7cf9f'
down_revision = 'd5edd32a9495'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPERUSER', 'LAB_ADMIN', 'EDITOR', 'SUBMITTER', 'VIEWER', name='role'), nullable=False),
    sa.Column('lab_name', sa.String(length=255), nullable=True),
    sa.Column('granted_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub', 'role', 'lab_name', name='uq_user_roles_sub_role_lab')
    )
    op.create_index('ix_user_roles_sub', 'user_roles', ['sub'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_roles_sub', table_name='user_roles')
    op.drop_table('user_roles')
    # ### end Alembic commands ###
