"""Add campaign journal entries

Revision ID: 361d200c0292
Revises: 391060b4292b
Create Date: 2026-10-05 20:48:17.252036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers used by Alembic.
revision = '361d200c0292'
down_revision = '391060b4292b'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_journal_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('entry', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_name'], ['campaigns.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_journal_entries_campaign_name'), 'campaign_journal_entries', ['campaign_name'], unique=False)
    # ### end Alembic commands ###

    # Move journals out of campaign meta into rows
    op.execute(
        "INSERT INTO campaign_journal_entries (campaign_name, entry, created_at) "
        "SELECT c.name, j.entry, now() "
        "FROM campaigns c, json_array_elements_text(c.meta -> 'optimizer' -> 'journal') WITH ORDINALITY AS j(entry, ord) "
        "WHERE json_typeof(c.meta -> 'optimizer' -> 'journal') = 'array' "
        "ORDER BY c.name, j.ord"
    )
    op.execute(
        "UPDATE campaigns SET meta = jsonb_set(meta::jsonb, '{optimizer}', (meta::jsonb -> 'optimizer') - 'journal')::json "
        "WHERE meta::jsonb -> 'optimizer' ? 'journal'"
    )

def downgrade():
    # Fold journal rows back into campaign meta
    op.execute(
        "UPDATE campaigns c SET meta = jsonb_set(c.meta::jsonb, '{optimizer,journal}', j.journal)::json "
        "FROM (SELECT campaign_name, jsonb_agg(entry ORDER BY id) AS journal "
        "FROM campaign_journal_entries GROUP BY campaign_name) j "
        "WHERE j.campaign_name = c.name AND c.meta::jsonb ? 'optimizer'"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_journal_entries_campaign_name'), table_name='campaign_journal_entries')
    op.drop_table('campaign_journal_entries')
    # ### end Alembic commands ###
