"""add meta to campaign_samples

Revision ID: 9e17cc7d66ae
Revises: b459a15d494d
Create Date: 2026-02-11 14:40:34.003625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers used by Alembic.
revision = '9e17cc7d66ae'
down_revision = 'b459a15d494d'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_samples', sa.Column('meta', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_samples', 'meta')
    # ### end Alembic commands ###
