"""add api tokens and user identities

Revision ID: a47b8bf03ce8
Revises: 7f5a39e7cf9f
Create Date: 2026-08-09 20:18:52.802286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers used by Alembic.
revision = 'a47b8bf03ce8'
down_revision = '7f5a39e7cf9f'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_sub', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_tokens_owner_sub', 'api_tokens', ['owner_sub'], unique=False)
    op.create_index('uq_api_tokens_token_hash', 'api_tokens', ['token_hash'], unique=True)
    op.create_table('user_identities',
    sa.Column('sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sub')
    )
    op.create_index('ix_user_identities_email', 'user_identities', ['email'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_identities_email', table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index('uq_api_tokens_token_hash', table_name='api_tokens')
    op.drop_index('ix_api_tokens_owner_sub', table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
