"""add input_files to tasks

Revision ID: d5edd32a9495
Revises: 12c04815567b
Create Date: 2026-06-01 17:04:51.104786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers used by Alembic.
revision = 'd5edd32a9495'
down_revision = '12c04815567b'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('input_files', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'input_files')
    # ### end Alembic commands ###
