user_dir: ./user
labs:
  - multiplication_lab
experiments:
  - optimize_multiplication

log_level: INFO

# Orchestrator web API configuration
web_api:
  host: localhost
  port: 8070

# PostgreSQL database configuration
db:
  host: localhost
  port: 5432
  username: ""
  password: ""

# MinIO file configuration
file_db:
  host: localhost
  port: 9004
  username: ""
  password: ""

# The minimum processing rate of the orchestrator.
# The lower the rate, the less CPU usage while idle but increases the latency
# of the first task to process.
orchestrator_min_hz: 0.5

# The maximum processing rate of the orchestrator.
# The higher the rate, the faster work is processed at the cost of increased CPU usage.
orchestrator_max_hz: 10