services:
  eos-postgresql:
    image: postgres:17.2
    container_name: eos-postgresql
    hostname: eos-postgresql
    restart: unless-stopped
    shm_size: 256mb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${EOS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${EOS_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - eos_network
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  eos-minio:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    container_name: eos-minio
    hostname: eos-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${EOS_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${EOS_MINIO_ROOT_PASSWORD}
    ports:
      - "9004:9000"
      - "9005:9001"
    networks:
      - eos_network
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

networks:
  eos_network:
    name: eos_network
    driver: bridge

volumes:
  postgresql_data:
    driver: local
  minio_data:
    driver: local
