"""Provision the EOS org, project, roles, apps, and service user in a freshly deployed Zitadel.

Runs inside a one-shot python container started by deploy.sh, with eos/auth/zitadel_bootstrap.py
mounted alongside it. The container talks to Zitadel over the compose network, while the EOS_ISSUER
written into the credentials file is the external origin EOS instances will use.

Every step is idempotent, so re-running deploy.sh against the same instance is safe.
"""

import os
import sys
from pathlib import Path

from zitadel_bootstrap import ORG_USER_MANAGER_ROLE, ZitadelBootstrapClient

OUT_FILE = "/out/eos-instance.env"


def _read_existing(path: str) -> dict[str, str]:
    """Parse a previous credentials file so re-runs reuse the API secret and PAT Zitadel won't re-reveal."""
    values: dict[str, str] = {}
    file = Path(path)
    if not file.exists():
        return values
    for line in file.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and "=" in stripped:
            key, value = stripped.split("=", 1)
            values[key.strip()] = value.strip()
    return values


def _write_credentials(values: dict[str, str], ui_url: str) -> None:
    """Write the EOS instance credentials, split into orchestrator (.env) and web UI (web_ui/.env) blocks."""
    content = f"""\
# EOS authentication credentials for this Zitadel instance.
# Generated by docker/zitadel/deploy.sh. Each EOS instance using this identity
# provider copies the blocks below into its own files. The web UI redirect URI
# was registered for: {ui_url}

# --- orchestrator: append to the EOS instance's .env ---
EOS_AUTH_ENABLED=true
EOS_AUTH_ISSUER={values["issuer"]}
EOS_AUTH_ORG_ID={values["org_id"]}
EOS_AUTH_PROJECT_ID={values["project_id"]}
EOS_AUTH_PAT={values["pat"]}
EOS_AUTH_INTROSPECTION_CLIENT_ID={values["api_client_id"]}
EOS_AUTH_INTROSPECTION_CLIENT_SECRET={values["api_client_secret"]}

# --- web UI: append to the EOS instance's web_ui/.env ---
# AUTH_SECRET is per instance; generate one with: openssl rand -base64 32
AUTH_ENABLED=true
AUTH_ISSUER={values["issuer"]}
AUTH_CLIENT_ID={values["web_client_id"]}
AUTH_ORG_ID={values["org_id"]}
AUTH_PROJECT_ID={values["project_id"]}
AUTH_PAT={values["pat"]}
AUTH_INTROSPECTION_CLIENT_ID={values["api_client_id"]}
AUTH_INTROSPECTION_CLIENT_SECRET={values["api_client_secret"]}
"""
    Path(OUT_FILE).write_text(content, encoding="utf-8")


def main() -> int:
    base_url = os.environ["BOOTSTRAP_BASE_URL"]
    issuer = os.environ["EOS_ISSUER"]
    ui_url = os.environ["EOS_UI_URL"].rstrip("/")
    admin_pat = os.environ["ADMIN_PAT"]
    dev_mode = ui_url.startswith("http://")

    existing = _read_existing(OUT_FILE)

    # API calls go through the compose network (base_url); the token issuer is the external origin.
    client = ZitadelBootstrapClient(base_url, admin_pat)
    try:
        client.wait_ready()
        client.disable_registration()
        org_id = client.ensure_org("EOS")
        project_id = client.ensure_project("EOS")
        client.ensure_project_role(project_id, "superuser")
        if os.environ.get("RELAX_PASSWORD_POLICY") == "true":
            client.relax_password_complexity()

        web_client_id = client.ensure_oidc_app(
            project_id, f"{ui_url}/api/auth/callback/zitadel", f"{ui_url}/signin", dev_mode
        )
        api_client_id, api_client_secret = client.ensure_api_app(project_id)

        user_id = client.ensure_machine_user("eos-user-admin")
        client.ensure_org_member(user_id, [ORG_USER_MANAGER_ROLE])

        # The API secret and PAT are only revealed once; reuse the previous file on re-runs.
        api_client_secret = api_client_secret or existing.get("EOS_AUTH_INTROSPECTION_CLIENT_SECRET", "")
        pat = existing.get("EOS_AUTH_PAT") or client.create_pat(user_id)
    finally:
        client.close()

    if not api_client_secret:
        print("  ! EOS API client secret is unknown (app pre-existed); delete the app and re-run", file=sys.stderr)

    _write_credentials(
        {
            "issuer": issuer,
            "org_id": org_id,
            "project_id": project_id,
            "web_client_id": web_client_id,
            "api_client_id": api_client_id,
            "api_client_secret": api_client_secret,
            "pat": pat,
        },
        ui_url,
    )
    print("  created org/project 'EOS', superuser role, Web UI + API apps, and the eos-user-admin service user")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
